CREATE TABLE "pg-drizzle_recipeIngredient" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_recipeIngredient_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recipeId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"amount" varchar(64),
	"unit" varchar(64),
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_recipeStep" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_recipeStep_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recipeId" integer NOT NULL,
	"instruction" text NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_recipe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_recipe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" text,
	"category" varchar(64),
	"cuisine" varchar(128),
	"difficulty" varchar(16),
	"prepTimeMinutes" integer,
	"cookTimeMinutes" integer,
	"servings" integer,
	"imageUrl" text,
	"notes" text,
	"sourceUrl" text,
	"deleted" boolean DEFAULT false NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_recipeIngredient" ADD CONSTRAINT "pg-drizzle_recipeIngredient_recipeId_pg-drizzle_recipe_id_fk" FOREIGN KEY ("recipeId") REFERENCES "public"."pg-drizzle_recipe"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_recipeStep" ADD CONSTRAINT "pg-drizzle_recipeStep_recipeId_pg-drizzle_recipe_id_fk" FOREIGN KEY ("recipeId") REFERENCES "public"."pg-drizzle_recipe"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_recipe" ADD CONSTRAINT "pg-drizzle_recipe_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "recipe_ingredient_recipe_id_idx" ON "pg-drizzle_recipeIngredient" USING btree ("recipeId");--> statement-breakpoint
CREATE INDEX "recipe_step_recipe_id_idx" ON "pg-drizzle_recipeStep" USING btree ("recipeId");--> statement-breakpoint
CREATE INDEX "recipe_created_by_idx" ON "pg-drizzle_recipe" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "recipe_name_idx" ON "pg-drizzle_recipe" USING btree ("name");--> statement-breakpoint
CREATE INDEX "recipe_deleted_idx" ON "pg-drizzle_recipe" USING btree ("deleted");