CREATE TABLE "drizzle_userFollow" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "drizzle_userFollow_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"followerId" varchar(255) NOT NULL,
	"followingId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "drizzle_userFollow" ADD CONSTRAINT "drizzle_userFollow_followerId_user_id_fk" FOREIGN KEY ("followerId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "drizzle_userFollow" ADD CONSTRAINT "drizzle_userFollow_followingId_user_id_fk" FOREIGN KEY ("followingId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_follow_follower_idx" ON "drizzle_userFollow" USING btree ("followerId");--> statement-breakpoint
CREATE INDEX "user_follow_following_idx" ON "drizzle_userFollow" USING btree ("followingId");--> statement-breakpoint
CREATE UNIQUE INDEX "user_follow_follower_following_idx" ON "drizzle_userFollow" USING btree ("followerId","followingId");