CREATE TABLE "drizzle_recipeNutrition" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "drizzle_recipeNutrition_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recipeId" integer NOT NULL,
	"caloriesKcal" integer,
	"proteinG" integer,
	"carbsG" integer,
	"fatG" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "drizzle_recipeNutrition" ADD CONSTRAINT "drizzle_recipeNutrition_recipeId_drizzle_recipe_id_fk" FOREIGN KEY ("recipeId") REFERENCES "public"."drizzle_recipe"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "recipe_nutrition_recipe_id_uidx" ON "drizzle_recipeNutrition" USING btree ("recipeId");