CREATE TABLE "drizzle_foodImportRun" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "drizzle_foodImportRun_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" varchar(16) NOT NULL,
	"sourceVersion" varchar(32) NOT NULL,
	"rowCount" integer DEFAULT 0 NOT NULL,
	"startedAt" timestamp with time zone NOT NULL,
	"finishedAt" timestamp with time zone,
	"status" varchar(16) NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "drizzle_food" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "drizzle_food_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" varchar(16) NOT NULL,
	"externalId" varchar(64) NOT NULL,
	"sourceVersion" varchar(32) NOT NULL,
	"name" varchar(512) NOT NULL,
	"nameEn" varchar(512),
	"language" varchar(8) NOT NULL,
	"foodGroup" varchar(256),
	"caloriesKcalPer100g" real,
	"proteinGPer100g" real,
	"carbsGPer100g" real,
	"fatGPer100g" real,
	"densityGPerMl" real,
	"gramsPerPiece" real,
	"gramsPerHead" real,
	"importedAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "food_import_run_source_idx" ON "drizzle_foodImportRun" USING btree ("source");--> statement-breakpoint
CREATE UNIQUE INDEX "food_import_run_source_running_uidx" ON "drizzle_foodImportRun" USING btree ("source") WHERE "drizzle_foodImportRun"."status" = 'running';--> statement-breakpoint
CREATE UNIQUE INDEX "food_source_external_id_uidx" ON "drizzle_food" USING btree ("source","externalId");--> statement-breakpoint
CREATE INDEX "food_name_idx" ON "drizzle_food" USING btree ("name");--> statement-breakpoint
CREATE INDEX "food_name_en_idx" ON "drizzle_food" USING btree ("nameEn");